version: "3"

networks:
  server:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.166.0/24

services:
  nginx:
    image: nginx:1.16.0-alpine
    restart: always
    networks:
      - server
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./php:/usr/share/nginx/html
      - ./nginx/log:/var/log/nginx
    ports:
      - "80:80"
    depends_on:
      - php
  php:
    image: php:7.3.6-fpm-alpine3.9
    restart: always
    networks:
      - server
    volumes:
      - ./php:/usr/share/nginx/html
